---

- hosts: all
  gather_facts: false
  tasks:
    - command: df -h
      register: diskinfo
    - name: list upgradeble
      shell: dnf check-update  | awk '(NR >=4) {print $1;}' | uniq
      args:
        warn: false
      register: pkginfo
    - command: echo " "{{ diskinfo }}" "{{ pkginfo }}" " | mail -s servinfo testing@cloudhat.com
