---

- hosts: all
  gather_facts: false
  tasks:
    - command: df -h
      register: diskinfo
    - name: list upgradeble
      shell: dnf check-update  | awk '(NR >=4) {print $1;}' | uniq
      args:
        warn: false
      register: pkginfo
    - command: echo " "{{ diskinfo.stdout_lines }}" "{{ pkginfo.stdout_lines }}" " | mail -s servinfo testing@somemail.com
