---

- hosts: all
  gather_facts: true
#  become: true
  collections:
  - community.general
  tasks:
#    - name: include secret vars file
#      include_vars: /etc/ansible/roles/mails.yml
    - name: disk free command and output
      command: df -h
      register: diskfree
    - name: pre patch info into var
      yum:
        list: "updates"
      become_user: root
      register: pkginfo
    - name: copy from var to file for diskfree
      local_action: copy content={{ diskfree.stdout }} dest=/tmp/ansible-diskfree-results.txt
    - name: copy from var to file for pkgs
      local_action: copy content="{{ pkginfo.results | map(attribute='name') | list }}" dest=/tmp/ansible-pkg-results.txt
