---

- hosts: all
  gather_facts: true
#  become: true
  collections:
  - community.general
  tasks:
#    - name: include secret vars file
#      include_vars: /etc/ansible/roles/mails.yml
    - name: disk free command and output
      command: df -h
      register: diskinf
      notify: Write
#    - name: copy from var to file for diskfree
#      local_action: copy content="{{ diskfree.stdout }}" dest="/opt/ansible-diskfree-results.txt"
   handlers:
     - name: Write
       copy:
         content: '{{ diskinf.stdout_lines }}'
         dest: /tmp/test.txt
       delegate_to: localhost
       run_once: true
     - debug:
         var: '{{ diskinf.stdout_lines }}'
