---

- hosts: all
  gather_facts: true
  serial: 1
#  become: true
  collections:
  - community.general
  tasks:
#    - name: include secret vars file
#      include_vars: /etc/ansible/roles/mails.yml
    - name: disk free command and output
      command: df -h
      register: diskinf
#    - name: copy from var to file for diskfree
#      local_action: copy content="{{ diskfree.stdout }}" dest="/opt/ansible-diskfree-results.txt"
    - name: Write linked_dirs file
      copy:
        content: '{{ diskinf }}'
        dest: /tmp/test.txt
      delegate_to: localhost
      run_once: true
    - debug:
        var: '{{ diskinf }}'
